### ISSUE TITLE
Latest recursive transform version producing blank Gcode

### ISSUE THREAD

**Issue by sirogi** [appmancer/JXPlotterXVG#5]
Hi!

Thank you for including the recursive transforms! However testing it with a purposefully transformed file, the old code produces proper looking Code with the expected offsets. 

With the same file, the new code seems to, well:

( Generated by XPlotterSVG version 1.1.0 - testing recursion )
M0
G21
G28
G90
G28
M1

is all she wrote

Feels like it only took one look, then went home :)

**Comment by appmancer** [comment]
Hi, sorry I've not been working the last couple of days.
This looks like it is using SVG elements that are unsupported, typically text.  If it was text, can you convert to a path first and try again?  Alternatively, the color of the stroke didn't match an entry in the materials file.
Can you share the SVG  and material file with me?

Thanks

**Comment by itsonlym3** [comment]
if you load an image (jpg, png, etc.) and issue an Path -> Trace Bitmap, you'll end up with the same result.  rastering of the image will handle everything, so there's no need to tweak the paths if you're just using an imported image.

**Comment by sirogi** [comment]
moving on, folks, nothing to see here. :)
user error, works flawlessly!

cheers!!
